version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: spring-todo-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring_todo_app
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

